### ISSUE TITLE
Unable to place comment on PR, when using different threshold values for mobile and desktop

### ISSUE THREAD

**Issue by basantPayU** [foo-software/foo-api#10]
I am currently trying to find a way to 
1. use separate thresholds for mobile and desktop devices
2. comment on PR, using lighthouse results of both mobile and desktop devices

```
on:
  pull_request:
    types: [opened, reopened]
    branches: [ main, feature/TCWEB-1382 ]
  # workflow_call:
  #   inputs:
  #     url:
  #       description: 'URL to check the Web Vitals for'
  #       type: string
  #       required: true

jobs:
  web_vitals_scan_desktop:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.FE_SLACK_WEBHOOK_URL }} #required to slack post

    steps:
        
      - uses: actions/checkout@master
      - run: mkdir  -p ${{ github.workspace }}/tmp/artifacts
      - name: Run Lighthouse
        id: lighthouseCheck
        uses: foo-software/lighthouse-check-action@master
        with:
          prCommentEnabled: true
          prCommentSaveOld: true
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
          urls: 'https://someURL/'
          device: desktop
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports desktop
          path: ${{ github.workspace }}/tmp/artifacts
      - name: Verify Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "85"
          minBestPracticesScore: "85"
          minPerformanceScore: "85"
          minProgressiveWebAppScore: "85"
          minSeoScore: "85"      
    
  web_vitals_scan_mobile:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}

  

    steps:
  
        
      - uses: actions/checkout@master
      - run: mkdir  -p ${{ github.workspace }}/tmp/artifacts
      - name: Run Lighthouse
        id: lighthouseCheckMobile
        uses: foo-software/lighthouse-check-action@master
        with:
          prCommentEnabled: true
          prCommentSaveOld: true
          gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          outputDirectory: ${{ github.workspace }}/tmp/artifacts
          urls: 'https://somURL'
          # url: ${{ inputs.url }}
          device: desktop
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports mobile
          path: ${{ github.workspace }}/tmp/artifacts
      - name: Verify Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheckMobile.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "55"
          minBestPracticesScore: "55"
          minPerformanceScore: "55"
          minProgressiveWebAppScore: "55"
          minSeoScore: "55"      
      
   

```
